### ISSUE TITLE
Port forwarding ignores protocol (udp)

### ISSUE THREAD

**Issue by mcaulfield** [pradels/vagrant-libvirt#260]
Working with a virtual machine that hosts a DHCP server listening on UDP port 67. Trying to forward from host:8067 to guest:67. It looks like vagrant-libvirt sets up a regular SSH TCP tunnel and ignores the protocol attribute.

From my Vagrantfile:
```
config.vm.network "forwarded_port", guest: 67, host: 8067, protocol: 'udp'
```

From ps -elf  | grep 8067:
```
4 S root      4205     1  0  80   0 - 19125 poll_s 10:28 pts/8    00:00:00 ssh -o User=vagrant -o Port=22 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ForwardX11=no -o IdentityFile=/root/.vagrant.d/insecure_private_key -L localhost:8067:192.168.121.102:67 -N 192.168.121.102
```

**Comment by infernix** [comment]
Since this is an SSH limitation and it's documented, closing.

**Comment by electrofelix** [comment]
Technically it is possible to route UDP over TCP, so it probably could be done by users that need this using the vagrant-trigger plugin to configure a command to setup socat on the host before vagrant up to redirect UDP traffic to a TCP port, have vagrant-libvirt do the TCP port forwarding, and a vagrant-trigger provision to execute the command in the guest to set up for TCP to UDP conversion to the correct port.

http://superuser.com/questions/53103/udp-traffic-through-ssh-tunnel suggests a few different approaches:
* fifo pipes with nc, or socat - programs need to remain running on both guest/host
* tun devices - must be created on start, and removed on destroy on both guest/host
* ssf - secure socket funnelling, dedicated program that is cmdline compatible with ssh, but again requires to available in guest/host.

Be a documentation only effort, I might see if it's possible to put something together to help users put together in their vagrant config to solve this.


One thing I did find that looks very interesting is that it might be possible to allow libvirt to handle all the port forwarding itself.

http://blog.adamspiers.org/2012/01/23/port-redirection-from-kvm-host-to-guest/, indicates that it might be possible to get libvirt itself to set up the necessary iptables rules on the host to do the necessary port forwarding, and support has been present since 0.8.8 (Feb 17 2011).

I'll see if I get a chance to look into this further.

**Comment by infernix** [comment]
Sure, it's technically possible - but the question here is should we support it in vagrant-libvirt and if yes, then how?

There's a strong case for using SSH portforwarding in that it works whenever SSH works - which is an implied fact for a vagrant config, regardless of the network configuration. The same can't be said of using iptables (depends on NAT config, gateway, and isn't controllable with libvirts nwfilter for this purpose); qemu hostfwd_add seems to only work with -net user so I am not sure if it works with bridged networking at all.

So if we're wrapping something in SSH, socat is the most obvious choice due to its availability in distro package managers. With TCP SSH forwarding we already spawn an ssh process anyway so it is in line with that. Unfortunately this will take up an additional TCP port too so that would have to be handled.

I especially like this one mentioned on that superuser thread: `ssh orig_strm_src socat udp4-listen:4003,reuseaddr,fork STDOUT| socat STDIN udp-sendto:localhost:4003` as it is a oneliner, but not sure if it is universally adaptable. 

If anyone can get this working reliably I'll gladly reopen, but we do need to handle checking for `socat` on both host and guest.

**Comment by electrofelix** [comment]
Not suggesting we should support one of the three listed methods, I would only considering noting them in documentation wish to point users in a direction to allow them to solve. Previous post is really just info for anyone searching for UDP port forwarding on vagrant-libvirt and just needs a pointer on where to go next.

For qemu hostfwd_add, I've yet to really investigate it's possibilities (I do have a bridged set up handy so I'll test that), so it's just a pointer for now in case I don't get to look at it and someone else is able to pick it up.

**Comment by nickbroon** [comment]
I ran into this problem. I'd added a UDP port forwarding config, but didn't see any error/warning displayed that it was being ignored. I think it's important that this error/warning is displayed, otherwise it makes diagnosing the problem non obvious.

**Comment by nickbroon** [comment]
The following would be very useful:

``` diff
diff --git a/lib/vagrant-libvirt/action/forward_ports.rb b/lib/vagrant-libvirt/action/forward_ports.rb
index 3e8b8c6d10eb..dfdfc6a12f9f 100644
--- a/lib/vagrant-libvirt/action/forward_ports.rb
+++ b/lib/vagrant-libvirt/action/forward_ports.rb
@@ -47,6 +47,11 @@ module VagrantPlugins
                              message_attributes
             ))
 
+            if fp[:protocol] == 'udp'
+              env[:ui].warn I18n.t('vagrant_libvirt.warnings.forwarding_udp')
+              next
+            end
+
             ssh_pid = redirect_port(
               @env[:machine],
               fp[:host_ip] || 'localhost',
diff --git a/locales/en.yml b/locales/en.yml
index 316f0c5ecc42..cd88b565ff57 100644
--- a/locales/en.yml
+++ b/locales/en.yml
@@ -54,6 +54,8 @@ en:
       ignoring_virtual_size_too_small: |-
         Ignoring requested virtual disk size of '%{requested}' as it is below
         the minimum box image size of '%{minimum}'.
+      forwarding_udp: |-
+        Forwarding UDP ports is not supported. Ignoring.
 
     errors:
       package_not_supported: No support for package with libvirt. Create box manually.
```
