### ISSUE TITLE
9p sync can produce mount_tag which is too long

### ISSUE THREAD

**Issue by alienth** [pradels/vagrant-libvirt#323]
If you have a folder sync with a path longer than 31 bytes, creation will fail due to the mount_tag being too long.

Example failing config:
```
myvm.vm.synced_folder "/tmp/blah", "/etc/puppet/environments/vagrant", type: '9p'
```

Error:
```
Call to virDomainCreateWithFlags failed: internal error: process exited while connecting to monitor: qemu-system-x86_64: -device virtio-9p-pci,id=fs0,fsdev=fsdev-fs0,mount_tag=/etc/puppet/environments/vagrant,bus=pci.0,addr=0x6: mount tag '/etc/puppet/environments/vagrant' (32 bytes) is longer than maximum (31 bytes)
```

**Comment by sciurus** [comment]
Thanks for reporting the problem. Any opinions on how we should fix it?

**Comment by alienth** [comment]
First thought that comes to mind would be truncating it and appending it with a numeric identifier to catch cases of similarly named mounts. However I haven't looked at the code yet so not sure that is viable.

If you were to truncate and use a numeric identifier, are there cases where another sync'd filesystem might be added to an existing VM without knowing the original mount is there? Pardon my ignorance - very new vagrant user.

**Comment by moozer** [comment]
I am having this specific problem also.
It used to work, but I think the problem started when I upgraded to vagrant version 1.7.2 form version 1.6.x. Using rsync instead of 9p works.

I looked in the coded, but not being very ruby literate, I couldn't see my way through the files i the plugin.
In which file is the 9p mount tag generated?
