### ISSUE TITLE
Support resizing of volume

### ISSUE THREAD

**Issue by twouters** [pradels/vagrant-libvirt#37]
Currently it doesn't seem to be supported to define volumesize for a new guest.
It wouldn't be hard to support though.
In `lib/vagrant-libvirt/action/create_domain_volume.rb` there's this:

    # Virtual size of image. Same as box image size.
    @capacity = env[:machine].box.metadata['virtual_size'] #G

IMO this could easily be extended to support a setting in Vagrantfile that defines the size of the new image.
The defined size shouldn't be smaller than the size specified in the box metadata.

Manual intervention on the guest machine would still be required though. (resizing partitions/filesystems)

**Comment by infernix** [comment]
This seems to have been merged a long time ago; I'm closing this, please create new issues if problems are found related to volume resizing.

**Comment by electrofelix** [comment]
Would automatic resizing of the filesystems be a separate issue?

**Comment by pronix** [comment]
@electrofelix  resizing fs is not problem of virtualisation tool. freebsd, linux, windows have different fs.

**Comment by infernix** [comment]
@electrofelix it would be; the volume resize is just a matter of passing a larger value to fog when the volume is created in a libvirt storage pool. So that's entirely abstracted away from vagrant-libvirt.

Filesystem resizing would involve looking at the volume itself, repartitioning it, resizing the filesystem etc. I don't think libvirt itself supports this at all; I use libguestfs for that type of work.

That type of functionality could be added but if that results in a dependency on libguestfs, that may not be something we'd want. I'd personally consider that to be outside the scope. If you really needed it, you could create a custom box and have that box do the resizing on first (or every) boot.
