### ISSUE TITLE
Question Regarding Username's Storage Pool

### ISSUE THREAD

**Issue by dgoodwin** [pradels/vagrant-libvirt#585]
Mostly just a question here. I noticed that something in the stack is creating a libvirt storage pool under the username I'm running vagrant as (dgoodwin) on Fedora 23. This storage pool appears to have a listing for every single file and directory in my home directory. 

I've discovered that if I remove any file, I can no longer vagrant up vm's due to a "Call to virStorageVolGetInfo failed", which can be fixed by a "virsh pool-refresh dgoodwin".

However I'm wondering about the storage pool in general, is it vagrant-libvirt doing this, what it's purpose is, and whether or not it's expected/safe?

Thanks!

**Comment by infernix** [comment]
Can you post a virsh dumpxml for that pool?

**Comment by dgoodwin** [comment]
Sure:

```
$ virsh pool-dumpxml dgoodwin
<pool type='dir'>
  <name>dgoodwin</name>
  <uuid>712f95a7-e1a1-4620-a157-07c12e091d6d</uuid>
  <capacity unit='bytes'>186298617856</capacity>
  <allocation unit='bytes'>153654558720</allocation>
  <available unit='bytes'>32644059136</available>
  <source>
  </source>
  <target>
    <path>/home/dgoodwin</path>
    <permissions>
      <mode>0710</mode>
      <owner>1000</owner>
      <group>1000</group>
      <label>unconfined_u:object_r:home_root_t:s0</label>
    </permissions>
  </target>
</pool>
```

**Comment by infernix** [comment]
I'm not really understanding how this is happening.

First of all, vagrant-libvirt will check if `config.storage_pool_name` exists. If you don't explicitly specify a `storage_pool_name` the default name would be `default` and not `$USER` - in your case `dgoodwin`. It will also only create this pool _if it is called_ `default`.

Secondly, if it were to create the storage pool, it is hardcoded to use `/var/lib/libvirt/images`.

Are you by chance specifying additional disks with 
```
domain.storage :file, :path => '/home/dgoodwin/foo.img'
```
or with some variable pointing to your homedir? Because you shouldn't be doing that. That includes ISOs connected to CDROM.

If not, please remove the pool from libvirt and then try to reproduce it with a `VAGRANT_LOG=debug vagrant up` and post the log here.

**Comment by dgoodwin** [comment]
I will do some more investigation, it's possible it's not even vagrant-libvirt, but something else in my stack. Closing for now, thank you for taking a look and clarifying it's not any known behavior in vagrant-libvirt.

FWIW I have not used domain storage in my home dir that I can recall.
